version: '2'
services:
  mutillidae:
    image: richarvey/nginx-php-fpm
    container_name: mutillidae
    ports:
      - 80:80
    volumes:
      - ./src:/var/www/html
    depends_on:
      - mysql

  mysql:
    image: mysql:5.6
    container_name: mysql
    environment:
      MYSQL_ROOT_PASSWORD: mutillidae
      MYSQL_DATABASE: mutillidae
    volumes:
      - ./data/mysql:/var/lib/mysql
