version: '2'
services:
  mutillidae:
    image: richarvey/nginx-php-fpm
    container_name: mutillidae
    ports:
      - 80:80
    volumes:
      - ./mutillidae:/var/www/html
    depends_on:
      - mysql

  hacker:
    image: richarvey/nginx-php-fpm
    container_name: hacker
    ports:
      - 81:80
    volumes:
      - ./hacker:/var/www/html

  server:
    image: richarvey/nginx-php-fpm
    container_name: server
    ports:
      - 82:80
    volumes:
      - ./server:/var/www/html

  mysql:
    image: mysql:5.6
    container_name: mysql
    environment:
      MYSQL_ROOT_PASSWORD: mutillidae
      MYSQL_DATABASE: mutillidae
    volumes:
      - ./data/mysql:/var/lib/mysql
